"""empty message

Revision ID: 0a665bb02483
Revises: 54c2039d6ac8
Create Date: 2020-05-06 17:41:41.918730

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0a665bb02483'
down_revision = '54c2039d6ac8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post', sa.Column('mark', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('post', 'mark')
    # ### end Alembic commands ###
