"""empty message

Revision ID: 32933ee371fa
Revises: 16ee182a6718
Create Date: 2020-05-05 20:42:33.789695

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '32933ee371fa'
down_revision = '16ee182a6718'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('slug', table_name='post')
    op.drop_column('post', 'slug')
    op.drop_column('post', 'title')
    op.drop_column('roles_users', 'confirmed_at')
    op.add_column('user', sa.Column('name', sa.String(length=100), nullable=False))
    op.alter_column('user', 'email',
               existing_type=mysql.VARCHAR(collation='utf8_unicode_ci', length=100),
               nullable=False)
    op.alter_column('user', 'password',
               existing_type=mysql.VARCHAR(collation='utf8_unicode_ci', length=255),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'password',
               existing_type=mysql.VARCHAR(collation='utf8_unicode_ci', length=255),
               nullable=True)
    op.alter_column('user', 'email',
               existing_type=mysql.VARCHAR(collation='utf8_unicode_ci', length=100),
               nullable=True)
    op.drop_column('user', 'name')
    op.add_column('roles_users', sa.Column('confirmed_at', mysql.DATETIME(), nullable=True))
    op.add_column('post', sa.Column('title', mysql.VARCHAR(collation='utf8_unicode_ci', length=140), nullable=True))
    op.add_column('post', sa.Column('slug', mysql.VARCHAR(collation='utf8_unicode_ci', length=140), nullable=True))
    op.create_index('slug', 'post', ['slug'], unique=True)
    # ### end Alembic commands ###
